INSERT INTO SELLER_FEEDBACK(ITEM_ID, SATISFACTION, ITEM_DELIVERY, ITEM_QUALITY, COMMENTS) VALUES(1, 10, 10, 10, "Great Product!");
INSERT INTO SELLER_FEEDBACK(ITEM_ID, SATISFACTION, ITEM_DELIVERY, ITEM_QUALITY, COMMENTS) VALUES(2, 5, 5, 6, "Mediocre service");
INSERT INTO SELLER_FEEDBACK(ITEM_ID, SATISFACTION, ITEM_DELIVERY, ITEM_QUALITY, COMMENTS) VALUES(6, 10, 10, 10, "Totally awesome mexican food! Best ever!");

