INSERT INTO ADMINISTRATOR (USERNAME, PASSWORD) VALUES ('AZurn', 'AZurn');
INSERT INTO ADMINISTRATOR (USERNAME, PASSWORD) VALUES ('Andrew', 'Zurn');
INSERT INTO ADMINISTRATOR (USERNAME, PASSWORD) VALUES ('Foo', 'Bar');
