SELECT I.ITEM_ID, I.ITEM_NAME, I.CREATOR_ID AS SELLER_ID, I.AUCTION_END, currentBid(I.ITEM_ID) AS WINNING_BID
FROM ITEM I, AUCTIONS A 
WHERE I.ITEM_ID = A.ITEM_ID AND A.USER_ID = 90 AND I.AUCTION_END < NOW() AND 
	A.MAXIMUM_BID = (SELECT MAX(MAXIMUM_BID)
					 FROM AUCTIONS A2
					 WHERE A2.ITEM_ID = I.ITEM_ID)
GROUP BY I.ITEM_ID, I.ITEM_NAME, I.CREATOR_ID, I.AUCTION_END;
