DROP TRIGGER IF EXISTS UPDATE_ITEM_CURRENT_WINNER;
delimiter &&
CREATE TRIGGER UPDATE_ITEM_CURRENT_WINNER
BEFORE INSERT ON AUCTIONS
	FOR EACH ROW
	BEGIN
	
		declare oldMaxBid int;
		declare itemStatus varchar(16);
	
		SELECT MAX(MAXIMUM_BID) into oldMaxBid
		FROM AUCTIONS
		WHERE ITEM_ID = NEW.ITEM_ID;
	
		SELECT STATUS into itemStatus
		FROM ITEM
		WHERE ITEM_ID = NEW.ITEM_ID;
	
		IF( itemStatus = 'Open' AND NEW.MAXIMUM_BID > oldMaxBid ) THEN
			UPDATE ITEM SET WINNER_ID = NEW.USER_ID WHERE ITEM_ID = NEW.ITEM_ID;
		END IF;	
	
	END &&
delimiter ;
