drop view IF EXISTS SALES_REPORT;
CREATE VIEW SALES_REPORT AS
	SELECT  CATEGORY, ITEM_ID, ITEM_NAME, CURRENT_BID AS FINAL_SELLING_PRICE, CURRENT_BID*.2 AS COMMISSION
	FROM ITEM 
	WHERE AUCTION_END < NOW() AND STATUS = 'SOLD';
